name: Sync Folgen
on:
  schedule:
    - cron: '0 5 * * 5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Folgen
        run: |
          curl --request GET \
          --url '${{ env.SITE_URL }}/api/sync/folgen' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
      - name: Sync Folgen
        run: |
          curl --request GET \
          --url '${{ env.SITE_URL }}/api/sync/inhalte' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
