name: Sync Folgen
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Folgen
        run: |
          curl --request GET \
          --url 'https://www.ddfdb.de/api/sync/folgen' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
      - name: Sync Inhalte
        run: |
          curl --request GET \
          --url 'https://www.ddfdb.de/api/sync/inhalte' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
      - name: Sync Deezer
        run: |
          curl --request GET \
          --url 'https://www.ddfdb.de/api/sync/deezer' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
