name: Sync Folgen
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 5'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🔄️ Sync production
        uses: ./.github/actions/sync
        with:
          ACTION_KEY: ${{ secrets.ACTION_KEY }}
          BASE_URL: 'https://www.ddfdb.de'

      - name: 🔄️ Sync development
        uses: ./.github/actions/sync
        with:
          ACTION_KEY: ${{ secrets.ACTION_KEY }}
          BASE_URL: 'https://development.ddfdb.de'
